###  Listar todas as motos
GET http://localhost:5000/api/Motorcycles
Accept: application/json

###

###  Criar moto
POST http://localhost:5000/api/Motorcycles
Content-Type: application/json

{
  "model": "Honda CG 160 Start",
  "plate": "AAA0B11",
  "year": 2024
}

###

###  Listar todos os entregadores
GET http://localhost:5000/api/Couriers
Accept: application/json

###

###  Criar entregador
POST http://localhost:5000/api/Couriers
Content-Type: application/json

{
  "name": "Carlos Pereira",
  "cnpj": "11122233000144",
  "birthDate": "1992-07-12",
  "cnhNumber": "6677889900",
  "cnhCategory": "A",
  "cnhImagePath": "/uploads/cnh/carlos.jpg"
}

###

###  Criar aluguel de moto
POST http://localhost:5000/api/Rentals
Content-Type: application/json

{
  "courierId": "GUID_DO_COURIER",
  "motorcycleId": "GUID_DA_MOTO",
  "planDays": 7,
  "dailyRate": 50.00
}

###

###  Devolver moto
POST http://localhost:5000/api/Rentals/return
Content-Type: application/json

{
  "rentalId": "GUID_DO_ALUGUEL",
  "returnDate": "2025-11-10"
}

###

###  Listar todos os aluguéis
GET http://localhost:5000/api/Rentals
Accept: application/json
